---
- name: Manage services on server
  hosts: server
  become: yes

  tasks:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

    - name: Check Nginx status
      command: systemctl is-active nginx
      register: result

    - name: Display result
      debug:
        msg: "Nginx is {{ result.stdout }}"
